name: riverpod_pagination_example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.8
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  retrofit: '>=4.0.0 <5.0.0'
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  custom_lint: ^0.5.7
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:

  uses-material-design: true